### ISSUE TITLE
User Story: View design process

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#1]
As **a Site User** I can **view a step by step design thinking process** so that **I can easily follow the process**

# Acceptance Criteria
  
* A Site User can view a summary of each design thinking step
* A Site User can view steps 1 to 3 and steps 4 to 7 in two sequenced pages which they can easily move between
  
# Tasks
- [x] Create the XperienceDezignWiz Project
- [x] Complete settings setup
- [x] Install necessary requirements
- [x] Save requirements.txt
- [x] Create the app dezignwixprocess
- [x] Create the Model for the Step data including a slug for each step
- [x] Create two views, one for the first step list page and one for the second step list page
- [x] Create the urls and the templates for the first page and the next page
- [x] Create a step template for the shared step elements
- [x] Use bootstrap and css to style templates
- [x] Add navigation arrows to move between first and next page
- [x] Add tooltips to the arrows and the links to the step details pages
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Add to Project

**Comment by Claire-Potter** [comment]
Completed
