### ISSUE TITLE
User Story: Update a Step

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#10]
As **a User** I can **update my step status and add comments** so that **I can track my progress through the Design Thinking journey.**

# Acceptance Criteria
  
* A Progress Status section is available to a logged in user within the Step Detail page
* A site visitor will see a default message within the section
* The user will be able to select and save a new progress status
* The status will reflect at the top of the Step Detail page as well as on the Step List page
* The user can create and save progress comments
* The comments will display in the Progress Status section on the Step Detail page
  
# Tasks

- [x] Create a model for the progress status data
- [x] Link the progress model to the step model through a ForeignKeyfield
- [x] Create a comment model for the comment data
- [x] Link the comment model to the step model through a ForeignKeyfield
- [x] Create a progress form for the user to update their progress status
- [x] Create a comment form for the user to add comments
- [x] Update the step detail view to display the progress status form and the comment form, the updated progress status and the captured comments. Ensure it only displays to logged in users
- [x] Update the step detail view to post the completed progress status form and comment form
- [x] Ensure that the progress status and comments only include those specific to the logged in user
- [x] Update the step details template with the content and styling for the Progress Status section
- [x] Update the step list view to display a default status if users are not logged in or have not updated their status or to display the updated status created by the user
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed
