### ISSUE TITLE
User Story: Return to Previous Page

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#12]
As **a User** I can **Return to the previous page** so that **When I follow an internal link, I can easily return to where I was within the design process**

# Acceptance Criteria
  
* Return links open the previous page that the user had open
* This is unless the link will create a loop, then it will return to the most logical page
* A user is always able to navigate back to where they were previously unless not possible to do so
  
# Tasks

- [x] Add return links using the correct tag in the template
- [x] Style the return links as buttons
- [x] Test that the return links direct the user to the previous page
- [x] If a loop between two pages is corrected, up date the return link to the most logical page url
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed
