### ISSUE TITLE
User Story: Progress Status

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#13]
As a **User** I can **update my step progress status and it will reflect correctly across all site pages** so that **I can compare my progress across the steps**.

# Acceptance Criteria
  
* Visitors have the status 'Not Started' per step across all pages
* If a logged in user has not updated all statuses or a status, all statuses or each individual status not updated will reflect as 'Not Started'
* A  logged in user's status per step will reflect as selected status once updated
  
# Tasks

- [x] As the admin user create once off 'Not Started' statuses per step and save
- [x] In views and templates set up that the Not Started status will appear to all site visitors across all pages
- [x] In views and templates set up that the Not Started status will appear if a logged in user has not as yet udated a status
- [x] In views and templates set up that a logged in user's status will appear as selected status once selection has been made and saved
- [x] Test all scenarios across the Step Lists and the Step Details pages

**Comment by Claire-Potter** [comment]
Completed
