### ISSUE TITLE
User Story: Understand Site Purpose

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#14]
As a **Site User** I can **understand the site purpose** so that **my expectations of the site are set**

# Acceptance Criteria
  
* As soon as a user enters the site they should be presented with the site purpose
* This should be easily understood and provide the necessary directions required
* The user should have an understanding about what to expect
  
# Tasks

- [x] Create an app called Home to store the home model with the home page image
- [x] Upload a simple image of the Design Thinking process
- [x] Create the alt attribute as the image name and save
- [x] Update the index.html template to include the image as well as a welcome paragraph
- [x] Add the descriptive content to the paragraph which contains the site purpose and a brief explanation
- [x] Ensure that the formatting and styling is pleasing
- [x] Add a Get Started link styled as a button which directs the user to the first page of Steps
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed
