### ISSUE TITLE
User Story: Login via Social Accounts

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#16]
As **a User** I can **login via my social media accounts** so that **I have single sign on benefit**
# Acceptance Criteria
  
* A user can select between their google or facebook accounts to login to the site
* The site will fetch their account details, validate them and create their social accounts
* The user successfully registers and continues to login using their social account details
  
# Tasks

- [x] Enable allauth social account settings for the site
- [x] Follow the google and facebook process to set up social account authorisations for the app
- [x] Set up the social accounts as Social applications
- [x] Login via social accounts to ensure that all functionality is working

**Comment by Claire-Potter** [comment]
Completed
