### ISSUE TITLE
User Story: Access Social Media Accounts

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#17]
As **a User** I can **access XperienceDezignWiz Social Media Accounts** so that **I don't have to search for them individually**

# Acceptance Criteria
  
* Social Media Icons appear within the page footer
* The icon contains a link to the various social media sites
* Clicking the icon will open the social media site on a new blank tab
  
# Tasks

- [x] Create the footer in base.html and include a social media icon per social media app
- [x] Set the link to the correct social media site
- [x] Set the link to open on a new tab
- [x] Test all changes
- [x] The social media site should display (no specific page for XperienceDezignWiz as this is a test site)

**Comment by Claire-Potter** [comment]
Completed on the site
