### ISSUE TITLE
User Story: Persona Tool

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#18]
As **a User** I can **create a Persona** so that **I can complete the persona template as part of the Empathy step**

# Acceptance Criteria
  
* A user can access the Persona tool from the step detail page
* A user can complete the customisable fields in the persona form
*  A user can browse through potential persona images to select a persona image
* A user can select a survey, the default question % answers will create generic persona fields:
    * Age
    * Gender
    * Industry
* A user can save their persona
  
# Tasks

- [ ] Utilise the Code Institute Persona Template to create a persona model and form
- [ ] Create a view, a url and a template to render the persona page
- [ ] Create an image model to store the persona image gallery images
- [ ] Create an array in javascript for the user to browse between the images, select an image and save it
- [ ] Create a ForeignKey field to display the user's surveys and allow the user to select one survey from the persona model
- [ ] Create a ForeignKey field to display the default answer options
- [ ] Create correlated fields in the persona template that will display:
- [ ] Age - highest percentage selected
- [ ] Gender - highest percentage selected
- [ ] Industry - highest percentage selected
- [ ] Test all changes
