### ISSUE TITLE
User Story: Summary view of step detail sections

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#19]
As **a User** I can **view the summarised sub-sections of a step from the step process summary page** so that **I can easily overview 1. My progress within each step, 2. How many resources are available per step 3. How many tools are available per step**

# Acceptance Criteria
  
* Each step on the Step Lists includes the progress status with an updated status if applicable
* Each steop on the Step Lists includes a resources summary with the number of resources matching the number of linked resources per step
* Each step on the Step Lists includes a tools summary with the number of tools matching the number of linked tools per step
  
# Tasks

- [x] Create a filter that checks for all progress statuses, created by the logged in user
- [x] Condition as follows: if there is a progress status created by the logged in user, the most recent (latest) status will be returned, if not, the most 
recent (latest) status for the step created by the admin user as a default status would be returned
- [x] Add else condition: if the page is being viewed by a user who is not logged in, all statuses will reflect as Not Started
- [x] Create within the step model a count of the number_of_tools by counting the number of tools selected in the tools
        field and returning it as an integer. This is displayed through the first.html template and the next.html template
- [x]  Create within the step model a count of the number_of_resources by counting the number of resources selected in the resources field and returning it as an integer. This is displayed through the first.html template and the next.html template
- [x] Update the templates with the necessary html and css
- [x] Test all changes and conditions

**Comment by Claire-Potter** [comment]
Completed
