### ISSUE TITLE
User Story: Open a process step

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#2]
As **a Site User** I can **click on a step and open it** so that **I can access the content of the step**

# Acceptance Criteria
  
* Each step displays individually on a page
* Each step has a unique url link to open the Step page
* When the url is clicked, the Step detail page will open
  
# Tasks
- [x] Create the view and url to display the Step Detail
- [x] Create the Template - HTML and CSS - to display the styled content for the Step Detail
- [x] Test to ensure the Step List Displays, each link is unique and directs the user to the individual Step Detail page

**Comment by Claire-Potter** [comment]
Completed
