### ISSUE TITLE
User Story: Move between steps

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#20]
As **a User** I can **easily move back and fourth between steps** so that **I can updated my progress status for each step and access the step content as and when required.**

# Acceptance Criteria
  
* Navigation within the step details page directs the user between steps
* The previous page arrow will open the previous step
* The next page arrow will open the next step
* For the step Getting Started, the previous page arrow will go to the last step Finishing off
* For the step Finishing Off, the next page arrow will go to the first step Getting Started
* The user is able to circle back and fourth between all seven steps as required
  
# Tasks

- [x] Create if/elif/else statements within the step details view
- [x] Create conditions: the if/elif satements will check if the current step title field matches the given step title. If it does, the step_display_prev will reference the step slug that comes before the step_display_next will reference the step slug that comes next.
- [x] Ensure that: 'Getting Started references 'finishing-off' slug as step_display_prev and Finishing Off references the 'getting-started' slug to create a circular loop between the steps
- [x] Create the previous and next links displayed as icon buttons in the step detail template. Update html and style through bootstrap and CSS
- [x] Add tooltips: Tooltip code from W3 school tutorial and adapted for site
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed
