### ISSUE TITLE
User Story: Search for a Step

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#21]
As **a User** I can **search for a Step** so that **I can access each step as and when required**

# Acceptance Criteria
  
* A step search input field is available to the user across all pages
* When the user starts to type, they are prompted to select the correct step name
* The search displays the correct step searched for
* If a blank search or incorrect search term are run, all step pages links are returned for the user to choose between
  
# Tasks

- [x] Create the step search form as part of the navigation in base.html
- [x] Use bootstrap to and css to style
- [x] Create Javascript autoscript  to provide search prompts
- [x] Create a new view, url and template to display the search results
- [x] Use if/else statement to return different content if the user entered a blank search or searched for an incorrect term
- [x] Test all changes and ensure all links are working

**Comment by Claire-Potter** [comment]
Completed
