### ISSUE TITLE
User Story: Responsive site

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#22]
As **a User** I can **access the site across devices and across platforms** so that **no matter what device or platform I utilise, I can view and interact with the site and enjoy a similar experience**

# Acceptance Criteria
  
* The user can display the site across multiple devices and screensizes and the site will render accordingly 
* The user can access the site from various platfroms and the site will render accordingly
* The user's experience is similar across all devices and platforms
  
# Tasks

- [x] Use bootstrap, CSS and CSS media queries to ensure each template is responsive for different screen sizes
- [x] Continuously check changes within the google device toolbar to ensure the page is displaying for the various screen sizes
- [x] Conduct full site testing of screen size and platforms

**Comment by Claire-Potter** [comment]
Completed
