### ISSUE TITLE
User Story: System Messages

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#23]
As **a User** I can **receive system messages** so that **I can know if an action has been completed successfully**

# Acceptance Criteria
  
* When a form is saved a system message will display
* When a user logs in or out, a system message will display
* The system message displays the correct content and will automatically clear from the page
  
# Tasks

- [x] Set up django.contrib.messages in settings
- [x] Create an Alert messages container on base.html template style with bootstrap and css
- [x] Add the necessary message alert triggers to different views
- [x] Add a javascript function to automatically close the message
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed
