### ISSUE TITLE
User Story: Create a Survey

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#24]
As **a User** I can **create a new survey** so that **I can interact with customers/clients/users of my product to gather data and receive user input/feedback**

# Acceptance Criteria
  
* When a user is logged in they have access to the survey tool from the Empathy page
* They also can access the survey tool from the Survey menu link. A non-logged in user will be directed to the login page.
* When the user opens the Survey page, they will see a list of their created surveys, if already created.
* The user will have the option to create a new survey
* When the user selects the option to create a new survey, the Customise your own Design Thinking Survey page opens
* The user will enter and save a Survey Title to the Survey form and select create to save the form
  
# Tasks

- [x] Create a new app called dezigntools to save all Survey models, views and templates within
- [x] Create the Survey model and all fields to save survey data to
- [x] Create the views, url and templates for the survey list page and the create survey page
- [x] Add all styling through bootstrap and css pages
- [x] Ensure the views only display to logged in users
- [x] Ensure that all created surveys by a user will return to the users list page
- [x] Add link to the survey list from the empathy step detail page and add survey to the navigation menu
- [x] Check that all links open the correct pages
- [x] Add the Create Survey link styled as a button and add link to the create survey page
- [x] Create the Survey form which the user will use to add a new survey
- [x] Create post options within the view
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed
