### ISSUE TITLE
User Story: Predefined Questions

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#25]
As **a User** I can **include predefined questions and answers** so that **it simplifies the survey creation process by providing generic questions and options**

# Acceptance Criteria
  
* The user will be presented with the predefined questions and associated answer options
* The user will be able to read through th content
* The user will choose to accept the default questions and options
* The default questions and options will now be included in their survey
  
# Tasks

- [x] Create the models for the default age, gender and industry questions
- [x] Create the models for the default age, gender and industry options
- [x] Create a default options model and add the default questions to the model as ForeignKeyfields and the default answer options to the model as ManytoManyfields. The questions and options will be linked to the user's survey through this model.
- [x] Add an active field as a Booleanfield.
- [x] Create a defaultoptions form for the user to select to activate the options through
- [x] Create an default options create view and add the instructions to fetch the data as well as instructions to post the data to populate the various fields
- [x] Create the url and template. Add all styling as bootstrap and css
- [x] Add the accept button to the form to activate the default question options
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed
