### ISSUE TITLE
User Story: Survey - add own content

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#26]
As **a User** I can **add my own questions and answer options** so that **I can customise the survey according to my project requirements whilst still being able to analyse the feedback once received**

# Acceptance Criteria
  
* A user can add their own question content and save their content
* A user can add answer options per question and save their content
* A user can continue adding questions and options until their requirements have been met
* The questions and correct options will be included in the survey for the surveyee to answer as radio buttons to ensure that the feedback can still be analysed

# Tasks

- [x] Create a question model for the user to save their questions to
- [x] Create an options model for the user to save their options to
- [x] Create the relationship to the survey by adding the survey model as a ForeignKey field in the question model
- [x] Create the relationship to the question by adding the question model as a ForeignKey field in the option model
- [x] Create the question view, url and template. Format and style template with bootstrap and css
- [x] Create the option view, url and template. Format and style template with bootstrap and css
- [x] Create a question form for the user to capture their question content through
- [x] Create an option form for the user to capture their options through
- [x] Create the survey edit view, if the request method is not post, i.e. the user doesn't submit their question and opions forms and activate their survey, return survey edit page, with the questions and options that the user has already added
- [x] Make sure that only a logged in user can access the question and option pages
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed
