### ISSUE TITLE
User Story: Send out Survey

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#27]
As **a User** I can **send out the Survey directly from within the site to multiple email addresses** so that **I can manage sending the survey and receiving feedback from one platform with ease**

# Acceptance Criteria
  
* Once the user has activated the survey they are directed to a page to send out the survey via email
* A default subject will be suggested as 'XperienceDezignWiz Survey', however, the user can still update the subject
* The user is able to capture multiple email addresses to send the survey out to.
* The user is able to add content to the default message: You have been sent a survey to complete.
* The survey url will be added to the email for the user
* The user can send out their message and receive a confirmation 
* The email will be delivered to viable email addresses
  
# Tasks

- [x] Validate the XperienceDezignWiz domain via google cloud
- [x] Activate Sendgrid via google cloud and create a Sendgrid account
- [x] Update settings with Sendgrid settings and add the Sendgrid key to env.py and heroku config auths
- [x] Set up email integration and create an email template on Sendgrid
- [x] Create an email form for the user to capture the email content via
- [x] Create a view to fetch the email form, fetch the user's survey and create the url for the survey, If the form is posted, validate all fields and add additional content, connect to the sendgrid template to send through the email content and send the email via the Sendgrid application
- [x] Create a url and a template for the email page
- [x] Add link to the send email page and return link to the survey lists page
- [x] Add all styling as bootstrap and css
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed
