### ISSUE TITLE
User Story: Review Survey Feedback

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#28]
As **a User** I can **review Survey feedback** so that **I can understand my customer/client/users**

# Acceptance Criteria
  
* A user can view how many surveys have been submitted
* A user can view doughnut charts and tables containing the default question and answer data
* A user can view a summary of the questions they created and the options that users have chosen as a percentage
* A user can access the survey start page from the survey detail page

# Tasks

- [x] Create a view which fetches the specific survey created by the user, all survey submissions, all default option answers and all custom answers submitted
- [x] Create a url and template for the view
- [x] Link the page to the survey lists page so that the user can access the detail page from the list page
- [x] Style the detail page with bootstrap and css
- [x] Add the link to the start survey page
- [x] Create a new template to link through tags, for the chart-js script. Create three charts in chart-js, link default options answer data through the view and template tags
- [x] Add the tables to the template
- [x] Add the custom questions and answers for statement to the template
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed
