### ISSUE TITLE
User Story: Delete Survey

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#29]
As **a User** I can **delete a survey** so that **I have the option available if the survey is no longer required**

# Acceptance Criteria
  
* The user has the option to delete a survey from the survey list page
* The user can select to delete the survey
* The user deletes the survey and a success message is displayed
  
# Tasks

- [x] Create the view to fetch the survey, delete the survey and call the success message
- [x] Add the delete button to a form on the detail template and style
- [x] Test that when the delete button is clicked, the survey is deleted and te success message displays
- [ ] Task Four
- [ ] Task Five

**Comment by Claire-Potter** [comment]
Completed
