### ISSUE TITLE
User Story: Access Knowledge Resource

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#3]
As **a Site User** I can **access and play the resource video/s within the step** so that **I can re-view the learning material to understand the step within the process**

# Acceptance Criteria
  
* The video links are saved to the database
* The videos display within the Step Detail page
* The user can select to play the video and has control options
  
# Tasks

- [x] Create a model for the video links
- [x] Create a ManytoMany relationship within the Step model to select the relevant videos per Step
- [x] Update the Step Detail template with a for loop to return the video/s per step
- [x] Ensure the iframe does not enable autoplay and allows the user to utilise play controls
- [x] Create the Admin to ensure that a preview of the video displays
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed
