### ISSUE TITLE
User Story: Account Management

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#30]
As **a User** I can **perform simple account actions such as resetting my password, changing my email address, logging in and out** so that **I can easily access and update my account without having to reach out for support**

# Acceptance Criteria
  
* A new user can register for an account
* A user can login to their account and logout of their account
* A user can send a forgotten password email to themselves to reset their password
* A user can change their email address
* A user can add an additional email address
* A user can udpate their primary email address
* A user can validate their email address/es
  
# Tasks

- [x] Utilising the allauth.account templates, update html content, and style with bootstrap and css across templates
- [x] Ensure all links within templates are accurate and working
- [x] Create an account side-navigation par with bootstrap and javascript to collapse and display the different options when the user is on any of the account pages
- [x] Test that a user can register
- [x] Test that a user can login and logout
- [x] Test that a user can send a reset password email, receives it and that the link returns them to reset their password
- [x] Test that the user can utilise all of the update email address options

**Comment by Claire-Potter** [comment]
Completed
