### ISSUE TITLE
User Story: Site Administration

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#31]
As **a Site Administrator** I can **access the Admin site** so that **I can view/add/edit and delete content as required**

# Acceptance Criteria
  
* A Site Administrator will have the Admin site as a link within their navigation menu
* A Site Administrator will be able to edit the home page image and alt text saved as the name
* A Site Administrator will be able to edit the following Step fields: feature image, steps image, excerpt, body, resources and tools
* A Site Administrator will be able to add new tools and edit the following fields: excerpt, body and image
* A Site Administrator will be able to view only:
    * Default Questions
        * Age 
        * Gender
        * Industry
    * Default Options
        * Age
        * Gender
        * Industry
* A Site Administrator will be able to View/Delete:
    * Progress Status - users
    * Comments
    * Questions
    * Options
    *  Submissions
    * Default Question Answers
    * Answers
    * Contact Requests
 * A Site Administrator will be able to View/Edit/Delete:
    * All Steps Pages Images (Images)
    * Resources
    * Surveys
        
  
# Tasks
- [x]  Set up the admin.py views for the home app - home model
- [x] Add validations to admin.py to the home app - home model admin to remove delete permission
- [x] Set up the admin.py views for the home app -contact model
- [x] Add validations to admin.py to the home app -verification to remove delete and create permission
- [x] Set up the admin.py views for the dezignprocess app - step model
- [x] Add validations to admin.py to the dezignprocess app - step model admin to remove delete and add permission
- [x] Add validations to admin.py to the dezignprocess app - step model admin to make the following fields read only:
'title', 'slug', 'order_number', 'added', 'list_number', 'deletable'
- [x] Set up the  admin.py views for the dezignprocess app - tool model:
- [x] Add validations to admin.py to the  dezignprocess app - tool model admin to remove delete  permission
- [x] Add validations to admin.py to the designprocess app - tool model to make the following fields read only:
'title', 'slug', 'order_number', 'deletable'
- [x] Set up the admin.py views for the dezignprocess app - progress model:
- [x] Add validations to admin.py to the  dezignprocess app - progress model admin to remove add  permission
- [x] Add validations to admin.py to the designprocess app - progress model to make the following fields read only:
'name', 'email', 'step','updated_on', 'progress'
- [x] Set up the admin.py views for the dezignprocess app - comment model
- [x] Add validations to admin.py to the  dezignprocess app - comment model admin to remove add  permission
- [x] Add validations to admin.py to the designprocess app - progress model to make the following fields read only:
('name', 'email', 'step', 'created_on', 'body')
- [x] To all fields across all apps ensure that the following field is set up as editable=false in the model:
deletable = models.BooleanField(default=False, editable=False)
- [x] Set up the admin.py views for the dezignprocess app - resource model
- [x] Add validations to admin.py to the  dezignprocess app - resource model admin to remove add  permission
- [x] Add validations to admin.py to the designprocess app - resource model to make the following fields read only:
'name', 'email', 'step', 'created_on', 'body'
- [x] Set up the admin.py views for the dezignprocess app - image model
- [x] Add validations to admin.py to the  dezignprocess app - image model admin to remove add and delete  permission
- [x] Add validations to admin.py to the designprocess app - resource model to make the following fields read only:
'title', 'category'
- [x] Set up the admin.py views for the dezigntools app - survey model
- [x] Add validations to admin.py to the  dezigntools app - survey model admin to remove add  permission
- [x] Set up the admin.py views for the dezigntools apps - age, gender and industry  question and option models
- [x] Add validations to admin.py to the  dezigntools apps- age, gender and industry question and option models model admin to remove add, create and delete permission
- [x] Set up the admin.py views for the dezigntools apps -default option, question option, submission, answer and default answer models
- [x] Add validations to admin.py to the  dezigntools apps- default option, question, optionsubmission, answer and default answer models admin to remove add permission
- [x] To all fields across all apps ensure that the following field is set up as editable=false in the model:
deletable = models.BooleanField(default=False, editable=False)
- [x] From Admin site create the group Administrator to create the rest of the administrator permissions
- [x] Create AdminUser account as staff and link the Administrator user group
- [x] Add the Admin link to the navigation and restrict access to staff only
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed
