### ISSUE TITLE
User Story: SuperUser

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#34]
As **a SuperUser** I can **access the Admin Site** so that **I can provide admin support**
  
# Acceptance Criteria
  
* * A SuperUser will have the Admin site as a link within their navigation menu
* A SuperUser will have the same access as the Site Administrator and additional access
* A SuperUser will have no User Group restriction and will be able to access Accounts, Users and User Group, Social Accounts and additional access per DezignProcess and DezignTools App Admin
  
# Tasks

- [x] Create SuperUser and password
- [x] Access the admin site
- [x] Check that all site access works as per site admin tasks
- [x] Check that additional access works
