### ISSUE TITLE
User Story: Available tools

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#5]
As **a Site User** I can **access any step tools available ** so that **I can complete any documentation required for the step and understand how to implement the step**

# Acceptance Criteria
  
* The step tools data is saved to the database
* Each Step has the relevant step tools linked to the step
* The step tool is displayed in the step detail page and links to the relevant step tool page
*  The user can open the link to display the step tool content
* The user can return to the step detail page
  
# Tasks

- [x] Create the model for the step tool data, make sure each step tool has a slug
- [x] Create a ManytoManyRelationship tool within the Step model to link the relevant tools per step
- [x] Create a view and url for the Step Tool page
- [x] Create a Step Tool template, including HTML and CSS to display the step tool
- [x] Add a for loop to the Step Detail page to display each step tool added to the step
- [x] Ensure each step tool link contains the unique slug to open the correct step tool
- [x] Add a return button which references the previous page, to return to the correct Step Detail page from the tool
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed
