### ISSUE TITLE
User Story: Ideate Step guidance

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#7]
As **a Site User** I can **access a guide on how to setup free accounts and a high level overview of the third party software** so that **I can easily utilise the new software to complete the process**

# Acceptance Criteria
  
* A free third party platform which allows integration is selected
* The site's documentation is reviewed and reformatted to be added as an Ideate Step Tool
* The Tool is saved to the Tool model and displays against the ideate step
  
# Tasks

- [ ] Review free apps/platforms that provide whiteboard functionality / project boards / boards designed for the design thinking process
- [ ] Review their integration options
- [ ] Choose the app/ platform that provides the best fit / meets most needs
- [ ]  Review the available documentation and user guides
- [ ] Create a step tool and include the reformatted guidance
