### ISSUE TITLE
User Story: Account Registration

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Xperience-DezignWiz#9]
As **a User** I can **create a user account** so that **I can login as a user to access the survey feature and update and save my progress with comments**

# Acceptance Criteria
  
* The 'logged in status' will display to the user
* The user can register for an account
* The user can login to their account
* The user can logout of their account
* When logged in, the user now has additional access
  
# Tasks

- [x] Enable the django authorisations to be able to set up user accounts and utilise the default models, views and templates
- [x] Add the Login / Logout and Register navigation to the Navigation menu
- [x] Edit the default templates to render against base.html and update the HTML and styling to fit site 
- [x] Add limitations to views and templates to make sure the relevant sections and features are only available to a logged in user
- [x] Ensure that the user is directed to the log in page if they try to access content that requires an account
- [x] Ensure that success messages display when a user logs in and logs out
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed
